### PR TITLE
Remove deprecated xmldb function calls, fix save & delete user operations

### LINKED ISSUE #17: Cannot delete user
While trying to reproduce exist-db/exist#101 I found that I cannot delete a user.
There is a popup that the user account has been deleted but it persists even after multiple reboots. 
To reproduce:

- Create a new user "debugger".
- Create a new group "debug".
- Make sure debugger is the only member and manager of debug
- reboot
- log in as admin
(so far so good)

I can now delete the group debug, but not debugger no matter in what sequence, or when I reboot. The group is gone but the user stubbornly refuses to dissappear. 

Usermanager: 0.16.4
exist-db: 4.1.0

### PR DESCRIPTION
**Pull request by tuurma**
**Please review & merge ASAP**: The deprecated xmldb function calls have been deleted in eXist's develop branch, and are needed for compatibility with the forthcoming release of eXist 5.0.0-RC8.

Closes #17.

### CODE REVIEW

**Comment by joewiz** [comment]
@tuurma Could you confirm that you tested to confirm that your approach to user deletion works? It's somewhat different than mine (see https://github.com/eXist-db/usermanager/pull/21/files#diff-31c12b9f65cda0d28ef8d4febe7c4f16R879). If yours works too, then that's fine. I just wanted to confirm. 

@duncdrum @line-o You will recall #21 there was some discussion of supplying a test, which was beyond my abilities but which I had hoped you might be able to help. If you guys can help with a test, please do so as soon as possible, since we need to pull a release with this fix in ASAP to ensure the app doesn't break on RC8.

**Comment by tuurma** [comment]
Confirm I tested on my local and user deletion works. My approach mimics
the solution for deleting the group, so thought it's nice to have these
aligned but I have no opinion which would be more advisable really.

niedz., 14 kwi 2019, 02:11 użytkownik Joe Wicentowski <
notifications@github.com> napisał:

**Comment by wolfgangmm** [comment]
Maybe we could create a unit test with xqsuite to test the XQuery module functionality itself?

**Comment by tuurma** [comment]
@duncdrum @wolfgangmm it's unclear to me what changes are you requesting?

Solution for #17 is different than @joewiz's from c2d3b8e054426ffc8f44e1bef9ff2f5cd8ca888c but analogous to  @joern's treatment of deleting a group cf https://github.com/eXist-db/usermanager/blob/master/existdb-usermanager.html#L1053

Happy to add some xQuery tests but unclear what is it that should be tested exactly?

**Comment by duncdrum** [comment]
i think a xqsuite unit test for `login-helper.xql` would test that when a user is deleted we aren't left with dangling undeletable groups, and that the deletion is successful., i.e. the user is gone from `list-users`. 

An integration test for the usermanager would test that the button fires the right command, a pop-up is present, and that after confirmation the user no longer exists. 

For Xqsuite and WCT tests we would also need to configure travis to actually run these tests, for cypress we can simply add to the existing specs in e2e-core (there is already one for usermanager) in a separate PR there.

**Comment by wolfgangmm** [comment]
Test case: https://github.com/eXist-db/e2e-core/pull/13

**Comment by wolfgangmm** [comment]
@duncdrum now we have a preliminary test, can we get this merged so we can continue to actually test RC8?

**Comment by duncdrum** [comment]
@wolfgang go ahead I m traveling today and adjust the test in a separate pr tomorrow. Thx for the fixes.

**Pull request merged**
