### PR TITLE
[bugfix] include user info when deleting user

### LINKED ISSUE #17: Cannot delete user
While trying to reproduce exist-db/exist#101 I found that I cannot delete a user.
There is a popup that the user account has been deleted but it persists even after multiple reboots. 
To reproduce:

- Create a new user "debugger".
- Create a new group "debug".
- Make sure debugger is the only member and manager of debug
- reboot
- log in as admin
(so far so good)

I can now delete the group debug, but not debugger no matter in what sequence, or when I reboot. The group is gone but the user stubbornly refuses to dissappear. 

Usermanager: 0.16.4
exist-db: 4.1.0

### PR DESCRIPTION
**Pull request by joewiz**
As reported by @nsincaglia in [eXist-open](https://exist-open.markmail.org/thread/f5jrjuhewv7wbzdr):

> I am running eXist-db v4.3.1 with Usermanager Version: 0.16.4 installed. When I add a user it works fine. When I try to delete a user I receive a notice that the user was successfully deleted but the user remains in the system. Is there a fix for this issue? 
> 
> I am able to delete users using the Java Admin client but not with the Usernanager module. I really need to get the Usermanager module to be able to delete users so I would appreciate any help if anyone knows a fix.
> 
> Here is some more information about my instance.
> eXist Version:  4.3.1
> eXist Build:    201903250121
> Operating System:       Linux 4.14.104-78.84.amzn1.x86_64 amd64
> Java Version:   1.8.0_144
> Default Encoding:       UTF8
> Instance ID:    exist

Investigating this report, I was able to reproduce the error, so I opened Chrome Developer Tools and watched the Network pane to see the HTTP DELETE request to `/exist/apps/usermanager/api/user/`. I noticed the request included no username in the URL, and the payload was empty. Examining how other methods constructed their request, I noticed that the `_handleDeleteUser` method lacked a body. Adding the body fixed the problem, and I tested the fix and confirmed that it works: the URL includes the user name, the body includes the user record, and the account is successfully deleted. 

What masked the original invalid request is that `xmldb:delete-user` raises no error when it is given an argument of an empty string or a non-existent user. Switching to `sm:remove-user` would provide better error reporting, as it raises a proper `The user account with username foo does not exist` error. However, this PR fixes the original issue, so I'll submit this as is. A future PR should perhaps switch all uses of `xmldb` for user management to the securitymanager module. There are quite a few such calls in https://github.com/eXist-db/usermanager/blob/master/modules/userManager.

Closes #17.

### CODE REVIEW

**Comment by adamretter** [comment]
Just to add that those xmldb security functions will be removed in exist 5.0.0 as they have been deprecated for years.

**Comment by duncdrum** [comment]
@joewiz could you please include a test, so we can avoid future regressions

**Comment by JoernT** [comment]
i would rather not blocks this PR due to missing test. The solution is fine. 

We do not have an automated way of testing and the testing tools are still in flux. Further, the apps need to be migrated to Polymer3 anyway which also might have some influence on testing. 

Regarding the deprecated methods seemingly the userManager.xqm needs  a rewrite. When building the usermanager i've changed as less as possible just adapting it to the new UI. So essentially the code is the same as in the old dashboard (written by Adam i guess).

**Comment by duncdrum** [comment]
@JoernT care to elaborate what is in flux about polymer2 testing? its EOL, nothing changes. We also have automated tests in eXist-db/e2e-core, in addition to the test already in this repo. IIRC i offered setting up travis to run tests and build the app, but you didn't believe in those.

**Comment by JoernT** [comment]
> @JoernT care to elaborate what is in flux about polymer2 testing? its EOL, nothing changes. We also have automated tests in eXist-db/e2e-core, in addition to the test already in this repo. IIRC i offered setting up travis to run tests and build the app, but you didn't believe in those.

@duncdrum you obviously got me wrong. Nothing against testing  - in contrast. My statement was that i do not believe in PRs for such rather small projects. They do not guarantee any improvement in quality - just tests can do.

 But currently i myself neither have capacities nor testing-skill to do those myself. Same btw applies to dashboard, packagemanager, launcher apps.

**Comment by duncdrum** [comment]
nope i got the comment about PRs, i m referring to [this response](https://github.com/eXist-db/polymer-app-template/issues/3#issuecomment-402410940) about enabling building and running tests on travis.

> just tests can do.

My point exactly, deleting users is broken:
-   so lets add a test to make sure our solution keeps working, for when the inevitable poly3 update is coming.
-   whats the point of the tests in this repo, if we don't run them?

**Comment by JoernT** [comment]
> nope i got the comment about PRs, i m referring to [this response](https://github.com/eXist-db/polymer-app-template/issues/3#issuecomment-402410940) about enabling building and running tests on travis.
> 
> > just tests can do.
> 
> My point exactly, deleting users is broken:
> 
>     * so lets add a test to make sure our solution keeps working, for when the inevitable poly3 update is coming. Or the switch to security-manager upstream.
> 
>     * whats the point of the tests in this repo, if we don't run them?

@duncdrum don't know whatever position you think you have to push me into - the thread you're referring to had nothing to do with testing but dependency management (and is deprecated anyway nowadays). 

Second - i certainly never have voted against such testing. - i just have contributed the first versions of these apps and as they are open source everybody is free to contribute. It you set up this testing - fine. Nobody objects. However - just out of interest - why cypress? Obviously not all the tested apps are Polymer-ones but at least for these the 'built-in' WCT just does fine.

**Comment by duncdrum** [comment]
@JoernT i m not trying to push you to do anything. Deleting users is core functionality, it is broken (reported by me in April 2018). This PR addresses this but is missing a test to make sure that the fix works. Hence my comment to the PR.  

We repeatedly discussed the need for testing in the community call with respect to dashboard apps, you asked for feedback, so here it is. 

I couldn't care less about the framework or language of the test, I like cypress as it works for both shadow and light dom. You like another framework, thats great.

**Comment by line-o** [comment]
I would argue for this test to be an integration test. As it needs to be tested against a running DB to be as sure as we can be that the user action actually persists. Therefore, I would vote for e2c-core and cypress.

**Comment by joewiz** [comment]
@duncdrum @line-o Here were the steps I used to test. Is this helpful in preparing a counterpart PR containing a test in e2e-core?

1. Go to Dashboard at http://localhost:8080/exist/apps/dashboard/index.html
2. Click on User Manager at http://localhost:8080/exist/apps/usermanager/index.html (note that in 5.x, User Manager is embedded in Dashboard 2.0 so the URL and path to this app will differ)
3. When prompted to log in, enter admin user credentials
4. Click on the "+" icon to reveal the add user dialog
5. Click on the "User Name" field and enter "test"
6. Click on the "Save" button
7. The "User 'test' has been saved" message will appear. (We could confirm this is so with a direct call to `sm:user-exists("test")`, which should return `true()`.)
8. Click on the "test" user
9. Click on the "Delete User" button
10. When prompted with the "Really delete this user?" dialog, click "OK"
11. The "User 'test' has been deleted" message will appear. (We could confirm this is so with a direct call to `sm:user-exists("test")`, which should return `false()`.)

**Comment by lguariento** [comment]
Hi @joewiz - yes, I noticed the missing info too (see https://github.com/eXist-db/usermanager/issues/17#issuecomment-459527639). If you need help with testing this, please let me know!

**Comment by joewiz** [comment]
Superseded by #23.

**Pull request closed without merging**
