### PR TITLE
Int test

### PR DESCRIPTION
**Pull request by duncdrum**

### CODE REVIEW

**Comment by adamretter** [comment]
@duncdrum so the tests are failing currently, is that right?

**Comment by line-o** [comment]
@adamretter @duncdrum The tests fails with a 404 while trying to login. This could mean the database has not started, the dashboard was not installed or the URL points to the wrong endpoint

**Comment by duncdrum** [comment]
more like there were recent changes to the login code without adjusting the test. The db is up, dashboard installed, and the URL used to work. In other words, the test is accurately reporting a failure.

**Comment by line-o** [comment]
Looking at the changes in https://github.com/eXist-db/dashboard/commit/dde1b90ad61eae8d1120413e5a755b021291a2a3 , I assume the new login URL is now `/admin`.
@wolfgangmm do you agree?

**Comment by wolfgangmm** [comment]
> Looking at the changes in [eXist-db/dashboard@dde1b90](https://github.com/eXist-db/dashboard/commit/dde1b90ad61eae8d1120413e5a755b021291a2a3) , I assume the new login URL is now `/admin`.
> @wolfgangmm do you agree?

There's no `login.html` anymore. Instead a dialog will pop up from within the launcher.

**Comment by line-o** [comment]
@duncdrum I assume it is possible to just POST data to `/login` with cypress in order to login?

**Comment by duncdrum** [comment]
@line-o sure

**Comment by joewiz** [comment]
In today's Community Call, @duncdrum confirmed that the issue is related to the change of login URL for dashboard. Merging pending resolution of the underlying issue at https://github.com/eXist-db/dashboard/pull/99.

**Pull request merged**
